<template>
    <div class="pt-5">        
        <v-row class="pl-4">
            <v-col cols="2" class="pt-md-4 pl-md-4 pt-sm-3 px-0 py-0">
                <QuickLinks />
            </v-col>
            <v-col v-if="loading" cols="12" md="10">
                <v-card flat class="mt-6">
                    <div class="text-center blue--text text--darken-4 font-weight-bold">
                            Loading...         
                    </div>
                    <div class="mx-auto">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            style="
                            margin:auto
                            background: rgb(255, 255, 255);
                            display: block;
                            shape-rendering: auto;
                            animation-play-state: running;
                            animation-delay: 0s;
                            "
                            width="250px"
                            height="250px"
                            viewBox="0 0 100 100"
                            preserveAspectRatio="xMidYMid"
                        >
                            <circle
                            cx="50"
                            cy="50"
                            r="19"
                            stroke-width="5"
                            stroke="#002147"
                            stroke-dasharray="29.845130209103033 29.845130209103033"
                            fill="none"
                            stroke-linecap="round"
                            style="animation-play-state: running; animation-delay: 0s"
                            >
                            <animateTransform
                                attributeName="transform"
                                type="rotate"
                                dur="1s"
                                repeatCount="indefinite"
                                keyTimes="0;1"
                                values="0 50 50;360 50 50"
                                style="animation-play-state: running; animation-delay: 0s"
                            ></animateTransform>
                            </circle>
                            <circle
                            cx="50"
                            cy="50"
                            r="13"
                            stroke-width="5"
                            stroke="#4270a9"
                            stroke-dasharray="20.420352248333657 20.420352248333657"
                            stroke-dashoffset="20.420352248333657"
                            fill="none"
                            stroke-linecap="round"
                            style="animation-play-state: running; animation-delay: 0s"
                            >
                            <animateTransform
                                attributeName="transform"
                                type="rotate"
                                dur="1s"
                                repeatCount="indefinite"
                                keyTimes="0;1"
                                values="0 50 50;-360 50 50"
                                style="animation-play-state: running; animation-delay: 0s"
                            ></animateTransform>
                            </circle>
                            <!-- [ldio] generated by https://loading.io/ -->
                        </svg>
                    </div>
                </v-card>
            </v-col>
            <v-col v-else cols="12" md="10">
                <v-card flat class="mx-0 my-0">
                    <v-card-title
                        class="text-h5 font-weight-bold blue-grey--text text--darken-3 pb-2 pl-md-2 pt-md-1 pl-sm-5 pt-sm-0 pr-sm-4 mb-md-0"
                    >
                        <v-icon large left color="blue-grey darken-3">mdi-information</v-icon>
                        About Us
                    </v-card-title>
                </v-card>
                <v-card v-for="(about_item, index) in about_items" :key="index" flat class="my-md-1 ml-md-0 mr-3">
                    <v-card-text
                        class="text-h5 font-weight-bold pb-0 blue-grey--text text--darken-3 ml-2 ml-sm-3"
                    >
                        <v-icon left large color="blue-grey darken-3">
                            {{ about_item.icon }}
                        </v-icon>
                        {{ about_item.name }}
                    </v-card-text>
                    <v-card-text
                        class="text-h5 font-weight-regular ml-7 ml-md-10 pr-16"
                    >
                       {{ about_item.content }}
                    </v-card-text>
                </v-card>
            </v-col>
        </v-row>
    </div>  
</template>

<script>
import QuickLinks from "./components/quicklinks";
export default {
    data: () => ({
        about_items: null,
        loading: true
    }),
    components: {
        QuickLinks
    },
    created(){
        axios.get("/api/about/content/frontend_index")
         .then((res) => {
            // console.log(res)
            this.about_items = res.data
            this.loading = false
         })
         .catch((error) => {
            // console.log(error)
            // this.errors = error.response.data.errors
            this.loading = false
         });
    }
};
</script>

<style></style>
