<template>
   <div>
      <v-app id="inspire">
        <div v-show="hideTopBar">
           <TopBar />
        </div>

         <v-main class="grey lighten-3">
               <router-view :key="$route.fullPath"></router-view>
         </v-main>

         <!-- Loading Animations by loading.io
          [ldio] generated by https://loading.io/ -->

         <Footer />

      </v-app>
   </div>
</template>

<script>
import TopBar from './components/topbar';
import Footer from './components/footer';
export default {
   components: {
      Footer, TopBar
   },
   data: () => ({
       hideTopBar: true,
   }),
   mounted(){
   },
   watch: {
      $route(to, from) {
         document.title = to.meta.title || "MIU IQAC";
      },      
   },
   created() {
   }
};
</script>

<style scoped>

</style>
