<template>
   <v-sheet class="px-2 py-2" color="grey lighten-3" min-height="500">
      <v-sheet
         v-if="loading1 && loading2"
         class="px-2 py-2"
         color="grey lighten-3"
         height="500"
      >
         <v-card flat class="mt-6 grey lighten-3">
            <div
               class="
                  text-center
                  blue--text
                  text--darken-4
                  font-weight-bold
                  mt-3
               "
            >
               Loading...
            </div>
            <div class="mx-auto grey lighten-3">
               <svg
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                  style="
                  margin:auto
                  background: rgb(255, 255, 255);
                  display: block;
                  shape-rendering: auto;
                  animation-play-state: running;
                  animation-delay: 0s;
                  "
                  width="250px"
                  height="250px"
                  viewBox="0 0 100 100"
                  preserveAspectRatio="xMidYMid"
               >
                  <circle
                     cx="50"
                     cy="50"
                     r="19"
                     stroke-width="5"
                     stroke="#002147"
                     stroke-dasharray="29.845130209103033 29.845130209103033"
                     fill="none"
                     stroke-linecap="round"
                     style="animation-play-state: running; animation-delay: 0s"
                  >
                     <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;360 50 50"
                        style="
                           animation-play-state: running;
                           animation-delay: 0s;
                        "
                     ></animateTransform>
                  </circle>
                  <circle
                     cx="50"
                     cy="50"
                     r="13"
                     stroke-width="5"
                     stroke="#4270a9"
                     stroke-dasharray="20.420352248333657 20.420352248333657"
                     stroke-dashoffset="20.420352248333657"
                     fill="none"
                     stroke-linecap="round"
                     style="animation-play-state: running; animation-delay: 0s"
                  >
                     <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;-360 50 50"
                        style="
                           animation-play-state: running;
                           animation-delay: 0s;
                        "
                     ></animateTransform>
                  </circle>
                  <!-- [ldio] generated by https://loading.io/ -->
               </svg>
            </div>
         </v-card>
      </v-sheet>
      <div v-else>
         <v-row class="mx-2">
            <v-col cols="12">
               <v-card flat tile class="mx-auto">
                  <v-card-subtitle
                     class="
                        text-center text-h3
                        blue--text
                        text--darken-4
                        grey
                        lighten-3
                        py-0
                        mb-2
                     "
                  >
                     ALL EVENTS
                  </v-card-subtitle>
               </v-card>
            </v-col>
            <v-col cols="12" class="pt-0">
               <v-card rounded="0" class="mb-2">
                  <v-alert
                     color="green accent-4"
                     class="px-0 py-0 mx-0 my-0"
                     rounded="0"
                     outlined
                     text
                  >
                     <v-card-title>
                        <v-icon left color="green accent-4">
                           mdi-calendar-star
                        </v-icon>
                        Upcoming Events
                     </v-card-title>
                  </v-alert>
               </v-card>
              
              <v-card v-if="upcoming_events.length === 0" rounded="0" class="mb-3 mx-3">
                  <v-alert
                     color="green accent-4"
                     class="px-3 py-4 mx-0 my-0"
                     rounded="0"
                     outlined
                     text
                  >
                  <v-row>                  
                    <v-col cols="12" class="pt-0 pb-0">
                      <div class="text-subtitle-1 font-weight-medium text-center">
                        <v-icon left color="green accent-4">
                           mdi-close
                        </v-icon>
                          No Upcoming Events
                      </div>
                    </v-col>                    
                  </v-row>
                  </v-alert>
               </v-card>
              
              <v-card v-else v-for="(upcoming_event, index) in upcoming_events" :key="index" :to="'/events/single_event/' + upcoming_event.id" rounded="0" class="mb-3 mx-3">
                  <v-alert
                     color="green accent-4"
                     class="px-3 py-4 mx-0 my-0"
                     rounded="0"
                     outlined
                     text
                  >
                  <v-row>                  
                    <v-col cols="12" md="9" class="pt-0 pb-0">
                      <div class="text-subtitle-1 font-weight-medium">
                        <v-icon left color="green accent-4" small>
                          mdi-calendar-arrow-right
                        </v-icon>
                          {{ upcoming_event.event_name }}
                      </div>
                    </v-col>
                    <v-col cols="12" md="3" class="pt-0 pb-0">
                      <div class="text-subtitle-1 font-weight-medium">
                        Date : {{ moment(upcoming_event.event_date).format('MMMM Do YYYY, h:mm a') }}
                      </div>
                    </v-col>
                  </v-row>
                  </v-alert>
               </v-card>               

              <v-card rounded="0" class="mb-2">
                <v-alert
                     color="deep-orange darken-2"
                     class="px-0 py-0 mx-0 my-0"
                     rounded="0"
                     outlined
                     text
                >
                    <v-card-title>
                      <v-icon left color="deep-orange darken-2">
                          mdi-calendar-remove
                      </v-icon>
                      Passed Events
                    </v-card-title>
                </v-alert>
              </v-card>

              <v-card v-if="passed_events.length === 0" rounded="0" class="mb-3 mx-3">
                  <v-alert
                      color="deep-orange darken-2"
                      class="px-3 py-4 mx-0 my-0"
                      rounded="0"
                      outlined
                      text
                  >
                  <v-row>
                    <v-col cols="12" class="pt-0 pb-0">
                      <div class="text-subtitle-1 font-weight-medium text-center">
                        <v-icon left color="deep-orange darken-2">
                            mdi-close
                        </v-icon>
                          No Passed Events
                      </div>
                    </v-col>                    
                  </v-row>
                  </v-alert>
                </v-card>

                <v-card v-else v-for="(passed_event, index) in passed_events" :key="index" :to="'/events/single_event/' + passed_event.id" rounded="0" class="mb-3 mx-3">
                    <v-alert
                      color="deep-orange darken-2"
                      class="px-3 py-4 mx-0 my-0"
                      rounded="0"
                      outlined
                      text
                    >
                    <v-row>                  
                      <v-col cols="12" md="9" class="pt-0 pb-0">
                        <div class="text-subtitle-1 font-weight-medium">
                          <v-icon left color="deep-orange darken-2" small>
                            mdi-calendar-arrow-left
                          </v-icon>
                            {{ passed_event.event_name }}
                        </div>
                      </v-col>
                      <v-col cols="12" md="3" class="pt-0 pb-0">
                        <div class="text-subtitle-1 font-weight-medium">
                          Date : {{ moment(passed_event.event_date).format('MMMM Do YYYY, h:mm a') }}
                        </div>
                      </v-col>
                    </v-row>
                    </v-alert>
                </v-card>
            </v-col>
         </v-row>
      </div>
   </v-sheet>
</template>

<script>
import moment from "moment";
export default {
   data: () => ({
      upcoming_events: [],
      passed_events: [],
      moment: moment,
      loading1: true,
      loading2: true,
   }),
   created() {
     // Get Upcoming Events
      axios
         .get("/api/events/upcoming/eventsbyeventtypeid/" + this.$route.params.id)
         .then((res) => {
            this.upcoming_events = res.data;
            this.loading1 = false;
         })
         .catch((error) => {
            console.log(error);
            // this.errors = error.response.data.errors
            this.loading1 = false;
         });

      // Passed Events
        axios
         .get("/api/events/passed/eventsbyeventtypeid/" + this.$route.params.id)
         .then((res) => {
            this.passed_events = res.data;
            this.loading2 = false;
         })
         .catch((error) => {
            console.log(error);
            // this.errors = error.response.data.errors
            this.loading2 = false;
         });
   },
};
</script>

<style>
</style>