<template>
   <v-card flat class="mx-3 pt-3">      
      <v-row>
         <v-col v-if="loading">
            <v-card flat class="mt-6">
               <div class="text-center blue--text text--darken-4 font-weight-bold">
                  Loading...
               </div>
               <div class="mx-auto">
                  <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        style="
                        margin:auto
                        background: rgb(255, 255, 255);
                        display: block;
                        shape-rendering: auto;
                        animation-play-state: running;
                        animation-delay: 0s;
                        "
                        width="250px"
                        height="250px"
                        viewBox="0 0 100 100"
                        preserveAspectRatio="xMidYMid"
                  >
                        <circle
                        cx="50"
                        cy="50"
                        r="19"
                        stroke-width="5"
                        stroke="#002147"
                        stroke-dasharray="29.845130209103033 29.845130209103033"
                        fill="none"
                        stroke-linecap="round"
                        style="animation-play-state: running; animation-delay: 0s"
                        >
                        <animateTransform
                           attributeName="transform"
                           type="rotate"
                           dur="1s"
                           repeatCount="indefinite"
                           keyTimes="0;1"
                           values="0 50 50;360 50 50"
                           style="animation-play-state: running; animation-delay: 0s"
                        ></animateTransform>
                        </circle>
                        <circle
                        cx="50"
                        cy="50"
                        r="13"
                        stroke-width="5"
                        stroke="#4270a9"
                        stroke-dasharray="20.420352248333657 20.420352248333657"
                        stroke-dashoffset="20.420352248333657"
                        fill="none"
                        stroke-linecap="round"
                        style="animation-play-state: running; animation-delay: 0s"
                        >
                        <animateTransform
                           attributeName="transform"
                           type="rotate"
                           dur="1s"
                           repeatCount="indefinite"
                           keyTimes="0;1"
                           values="0 50 50;-360 50 50"
                           style="animation-play-state: running; animation-delay: 0s"
                        ></animateTransform>
                        </circle>
                        <!-- [ldio] generated by https://loading.io/ -->
                  </svg>
               </div>
            </v-card>
         </v-col>
         <v-col v-else cols="12" class="px-md-6 py-md-4">            
            <v-carousel height="auto" show-arrows-on-hover cycle interval="5500" hide-delimiters>
               <v-carousel-item v-for="(item, index) in items" :key="index">
                  <v-img
                     :src="'/storage/carousel_images/' + item.carousel_image"
                     aspect-ratio="1.77"
                     max-height="700"
                  >
                     <v-container fill-height fluid class="px-0 py-0">
                        <v-layout fill-height align-end>
                           <v-flex>
                              <!-- For sm and up devices -->
                              <v-alert
                                 text
                                 color="black darken-2"
                                 class="
                                    font-weight-bold
                                    text-h6
                                    mb-0
                                    hidden-xs-only
                                 "
                                 tile
                                 max-height="100"
                              >
                                 <div
                                    class="
                                       font-weight-bold
                                       text-center text-body-1
                                    "
                                 >
                                    {{ item.carousel_title }}
                                 </div>
                                 <div class="text-center text-subtitle-2">
                                    {{ item.carousel_subtitle }}
                                 </div>
                              </v-alert>

                              <!-- For xs devices -->
                              <v-alert
                                 text
                                 color="black darken-2"
                                 class="text-h6 mb-0 py-1 hidden-sm-and-up"
                                 tile
                                 max-height="100"
                              >
                                 <div class="text-center text-subtitle-2">
                                    {{ item.carousel_title }}
                                 </div>
                                 <div class="text-center text-caption">
                                    {{ item.carousel_subtitle }}
                                 </div>
                              </v-alert>
                           </v-flex>
                        </v-layout>
                     </v-container>
                  </v-img>
               </v-carousel-item>
            </v-carousel>
         </v-col>
      </v-row>
      <v-row class justify="space-around ml-1 ml-md-0 mr-1 mr-md-3">
         <v-col v-if="!loading" cols="3">
            <QuickLinks />
         </v-col>
         <v-col v-if="!loading" cols="12" md="9" class="black mt-0 mt-md-3">
            <v-card class="pl-0 ml-0 mt-md-0">
               Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut
               eaque eius alias fugit cum obcaecati aliquam nihil facilis itaque
               dignissimos quis explicabo, voluptatem repudiandae et! Quod hic
               architecto fugit qui.
            </v-card>
         </v-col>
      </v-row>
   </v-card>
</template>

<script>
import QuickLinks from "./components/quicklinks";
// import TopNav from './topnav'
export default {
   data: () => ({
      items: [],
      loading: true
   }),
   components: {
      QuickLinks,
   },
   created() {

      axios
         .get("/api/publication_token/clear_tokens")

      axios
         .get("/api/carouselcontent/frontend_index")
         .then((res) => {
            // console.log(res);
            this.items = res.data;
            this.loading = false
         })
         .catch((error) => {
            // console.log(error);
            // this.errors = error.response.data.errors
            this.loading = false
         });
   },
};
</script>

<style></style>
