<template>
<div class="pt-3">
   <div v-if="loading">
      <v-card flat class="mt-6">
         <div class="text-center blue--text text--darken-4 font-weight-bold">
               Loading...         
         </div>
         <div class="mx-auto">
            <svg
               xmlns="http://www.w3.org/2000/svg"
               xmlns:xlink="http://www.w3.org/1999/xlink"
               style="
               margin:auto
               background: rgb(255, 255, 255);
               display: block;
               shape-rendering: auto;
               animation-play-state: running;
               animation-delay: 0s;
               "
               width="250px"
               height="250px"
               viewBox="0 0 100 100"
               preserveAspectRatio="xMidYMid"
            >
               <circle
               cx="50"
               cy="50"
               r="19"
               stroke-width="5"
               stroke="#002147"
               stroke-dasharray="29.845130209103033 29.845130209103033"
               fill="none"
               stroke-linecap="round"
               style="animation-play-state: running; animation-delay: 0s"
               >
               <animateTransform
                  attributeName="transform"
                  type="rotate"
                  dur="1s"
                  repeatCount="indefinite"
                  keyTimes="0;1"
                  values="0 50 50;360 50 50"
                  style="animation-play-state: running; animation-delay: 0s"
               ></animateTransform>
               </circle>
               <circle
               cx="50"
               cy="50"
               r="13"
               stroke-width="5"
               stroke="#4270a9"
               stroke-dasharray="20.420352248333657 20.420352248333657"
               stroke-dashoffset="20.420352248333657"
               fill="none"
               stroke-linecap="round"
               style="animation-play-state: running; animation-delay: 0s"
               >
               <animateTransform
                  attributeName="transform"
                  type="rotate"
                  dur="1s"
                  repeatCount="indefinite"
                  keyTimes="0;1"
                  values="0 50 50;-360 50 50"
                  style="animation-play-state: running; animation-delay: 0s"
               ></animateTransform>
               </circle>
               <!-- [ldio] generated by https://loading.io/ -->
            </svg>
         </div>
      </v-card>
   </div>
   <div v-else>
      <v-card flat v-if="news.length === 0" height="480" min-height="300">
         <v-container fill-height fluid>
            <v-row align="center" justify="center">
               <div class="text-center">
                  <h1>No News Has Been Added Yet !!</h1>
                  <h2>Add News From The Admin Panel.</h2>
               </div>
            </v-row>
         </v-container>
      </v-card>
      <v-row v-else class="mx-2 py-4">
         <v-col cols="12">
            <v-card flat tile class="mx-auto">
               <v-card-subtitle
                  class="
                     text-center text-h3
                     blue--text
                     text--darken-4                     
                     py-0
                     mb-2
                  "
               >
                  ALL NEWS
               </v-card-subtitle>
            </v-card>
         </v-col>
         <v-row class="mx-1">
            <v-col md="3" lg="2" class="hidden-sm-and-down">
               <QuickLinks />
            </v-col>
            <v-col cols="12" md="9" lg="10">
               <div v-for="(single_news, index) in news" :key="index" class="mb-3">
                  <v-card width="auto" height="120" outlined class="d-flex align-center pa-auto" :to="'/news/single_news/' + single_news.id" :style="cardBorderColor">
                     <v-avatar
                        size="100"
                        tile
                        rounded
                        class="ml-2"
                     >
                        <v-img                  
                           :src="'/storage/news_images/' + single_news.news_image"
                           :alt="single_news.news_title"
                           position="center center"                        
                        ></v-img>
                     </v-avatar>

                     <div>
                     <!-- Title For Xs -->
                        <v-card-title class="text-subtitle-1 font-weight-bold d-flex d-sm-none text-wrap">
                           {{ single_news.news_title | truncate_title_xs }}
                        </v-card-title>
                     <!-- Title For Sm -->
                        <v-card-title class="text-subtitle-1 font-weight-bold d-none d-sm-flex d-md-none text-wrap">
                           {{ single_news.news_title | truncate_title_sm }}
                        </v-card-title>
                     <!-- Title For Md -->
                        <v-card-title class="text-subtitle-1 font-weight-bold d-none d-md-flex d-lg-none text-wrap">
                           {{ single_news.news_title | truncate_title_md }}
                        </v-card-title>
                     <!-- Title For XL and up -->
                        <v-card-title class="text-subtitle-1 font-weight-bold d-none d-lg-flex d-xl-none text-wrap">
                           {{ single_news.news_title }}
                        </v-card-title>
                        <v-card-subtitle
                           class="font-weight-bold text-no-wrap"
                        > {{ moment(single_news.created_at).format('MMMM Do YYYY, h:mm a') }}
                        </v-card-subtitle>
                     </div>
                  </v-card>
               </div>
            </v-col>
         </v-row>
      </v-row>
   </div> 
</div>
</template>

<script>
import moment from 'moment'
import QuickLinks from "./components/quicklinks";
export default {
   data: () => ({
      news:[],
      moment: moment,
      loading: true,
   }),
   components: {
      QuickLinks,
   },
   computed: {
      cardBorderColor: function(){
         return {border: '1px solid #4270a9'}
      }
   },
   created() {
      axios
         .get("/api/news/frontend_index")
         .then((res) => {
            this.news = res.data;
            this.loading = false;
         })
         .catch((error) => {
            console.log(error);
            // this.errors = error.response.data.errors
            this.loading = false;
         });
   },
};
</script>

<style>
</style>