<template>
<div class="pt-3">
   {{news}}
      <div v-if="loading">
          <v-card flat class="mt-6">
              <div class="text-center blue--text text--darken-4 font-weight-bold">
                    Loading...         
              </div>
              <div class="mx-auto">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    style="
                    margin:auto
                    background: rgb(255, 255, 255);
                    display: block;
                    shape-rendering: auto;
                    animation-play-state: running;
                    animation-delay: 0s;
                    "
                    width="250px"
                    height="250px"
                    viewBox="0 0 100 100"
                    preserveAspectRatio="xMidYMid"
                >
                    <circle
                    cx="50"
                    cy="50"
                    r="19"
                    stroke-width="5"
                    stroke="#002147"
                    stroke-dasharray="29.845130209103033 29.845130209103033"
                    fill="none"
                    stroke-linecap="round"
                    style="animation-play-state: running; animation-delay: 0s"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;360 50 50"
                        style="animation-play-state: running; animation-delay: 0s"
                    ></animateTransform>
                    </circle>
                    <circle
                    cx="50"
                    cy="50"
                    r="13"
                    stroke-width="5"
                    stroke="#4270a9"
                    stroke-dasharray="20.420352248333657 20.420352248333657"
                    stroke-dashoffset="20.420352248333657"
                    fill="none"
                    stroke-linecap="round"
                    style="animation-play-state: running; animation-delay: 0s"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;-360 50 50"
                        style="animation-play-state: running; animation-delay: 0s"
                    ></animateTransform>
                    </circle>
                    <!-- [ldio] generated by https://loading.io/ -->
                </svg>
              </div>
          </v-card>
      </div>
      <div v-else>
         <v-card flat v-if="news.length === 0" height="480" min-height="300">
            <v-container fill-height fluid>
               <v-row align="center" justify="center">
                  <div class="text-center">
                     <h1>No Members Exist For This Section Yet !!</h1>
                     <h2>Add Members From The Admin Panel.</h2>
                  </div>
               </v-row>
            </v-container>
         </v-card>
         <v-row v-else class="mx-2 py-4">
            <v-col v-for="(single_news, index) in news" :key="index" cols="12">
               <v-card width="auto" outlined class="mt-2" to="/">
                  <v-list-item>                     
                     <v-img
                        min-height="100"
                        max-height="100"
                        min-width="70"
                        max-width="70"
                        :src="'/storage/news_images/' + single_news.news_image"
                        alt
                        position="center center"
                        class="my-3 mr-4"
                     ></v-img>                     

                     <v-list-item-content>
                        <div class="text-body-2 mt-1 font-weight-bold"> 
                           {{ single_news.news_title }}
                        </div>
                        <v-list-item-title class="text-subtitle-2 mt-1 font-weight-regular">
                           {{ single_news.news_subtitle }}
                        </v-list-item-title>
                        <v-list-item-subtitle
                           class="mb-1"
                        > {{ moment(single_news.created_at).format('MMMM Do YYYY, h:mm:ss a') }} </v-list-item-subtitle>
                     </v-list-item-content>
                  </v-list-item>
               </v-card>
            </v-col>
         </v-row>
      </div>
   </div>
</template>

<script>
import moment from 'moment'
export default {
   data: () => ({
      news:[],
      moment: moment,
      loading: true,      
   }),
   created() {
      axios
         .get("/api/news/frontend_index")
         .then((res) => {
            this.news = res.data;
            this.loading = false;
         })
         .catch((error) => {
            console.log(error);
            // this.errors = error.response.data.errors
            this.loading = false;
         });
   },
};
</script>

<style>
</style>