<template>
   <div class="pt-3">      
      <div v-if="loading">
          <v-card flat class="mt-6">
              <div class="text-center blue--text text--darken-4 font-weight-bold">
                    Loading...
              </div>
              <div class="mx-auto">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    style="
                    margin:auto
                    background: rgb(255, 255, 255);
                    display: block;
                    shape-rendering: auto;
                    animation-play-state: running;
                    animation-delay: 0s;
                    "
                    width="250px"
                    height="250px"
                    viewBox="0 0 100 100"
                    preserveAspectRatio="xMidYMid"
                >
                    <circle
                    cx="50"
                    cy="50"
                    r="19"
                    stroke-width="5"
                    stroke="#002147"
                    stroke-dasharray="29.845130209103033 29.845130209103033"
                    fill="none"
                    stroke-linecap="round"
                    style="animation-play-state: running; animation-delay: 0s"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;360 50 50"
                        style="animation-play-state: running; animation-delay: 0s"
                    ></animateTransform>
                    </circle>
                    <circle
                    cx="50"
                    cy="50"
                    r="13"
                    stroke-width="5"
                    stroke="#4270a9"
                    stroke-dasharray="20.420352248333657 20.420352248333657"
                    stroke-dashoffset="20.420352248333657"
                    fill="none"
                    stroke-linecap="round"
                    style="animation-play-state: running; animation-delay: 0s"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;-360 50 50"
                        style="animation-play-state: running; animation-delay: 0s"
                    ></animateTransform>
                    </circle>
                    <!-- [ldio] generated by https://loading1.io/ -->
                </svg>
              </div>
          </v-card>
      </div>
      <div v-else>
         <v-card flat v-if="members.members.length === 0" height="480" min-height="300">
            <v-container fill-height fluid>
               <v-row align="center" justify="center">
                  <div class="text-center">
                     <h1>No Members Exist For This Section Yet !!</h1>
                     <h2>Add Members From The Admin Panel.</h2>
                  </div>
               </v-row>
            </v-container>
         </v-card>
         <div v-else>
            <v-row>
               <v-card flat tile class="mx-auto mt-1">
                  <v-card-title class="text-center text-h3 blue--text text--darken-4">{{ members.name }}</v-card-title>
               </v-card>            
            </v-row>

            <v-row class="mx-4 pb-4">
               <v-col
                  v-for="(member, index) in members.members"
                  :key="index"
                  cols="12"
                  sm="6"
                  md="4"
               >
                  <v-card min-height="450" elevation="10" color="grey lighten-4">
                     <v-img                        
                        width="auto"
                        :src="'/storage/member_images/' + member.member_image"
                        alt=""
                        class="mx-auto"
                        position="center center"
                        aspect-ratio="0.9"
                     ></v-img>
                     <div class="py-2">
                        <v-card-subtitle class="text-subtitle-1 font-weight-medium blue--text text--darken-4 py-1">
                           <v-icon left color="blue darken-4">
                              mdi-account
                           </v-icon>
                           Name: {{ member.name }}
                        </v-card-subtitle>
                        <v-card-subtitle class="text-subtitle-1 font-weight-medium blue--text text--darken-4 py-1">
                           <v-icon left color="blue darken-4">
                              mdi-briefcase
                           </v-icon>
                           Designation: {{ member.designation }}
                        </v-card-subtitle>
                        <v-card-subtitle class="text-subtitle-1 font-weight-medium blue--text text--darken-4 py-1">
                           <v-icon left color="blue darken-4">
                              mdi-email
                           </v-icon>
                           E-mail: {{ member.email }}
                        </v-card-subtitle>
                        <v-card-subtitle class="text-subtitle-1 font-weight-medium blue--text text--darken-4 py-1">
                           <v-icon left color="blue darken-4">
                              mdi-phone
                           </v-icon>
                           Contact No: {{ member.cell_number }}
                        </v-card-subtitle>
                     </div>                  
                  </v-card>
               </v-col>
            </v-row>

         </div>
      </div>
   </div>
</template>

<script>
export default {
   data: () => ({
      members: [],      
      loading: true,
   }),
   created() {

      axios
         .get("/api/people/show/" + this.$route.params.id)
         .then((res) => {
            this.members = res.data;
            this.loading = false;
         })
         .catch((error) => {
            // console.log(error);
            // this.errors = error.response.data.errors
            // this.loading = false;
            this.$router.push({ name: 'ResourceNotFound' })
         });
   },
};
</script>

<style></style>
