<template>
<div class="pt-3">   
   <div v-if="loading">
         <v-card flat class="mt-6">
            <div class="text-center blue--text text--darken-4 font-weight-bold">
                  Loading...         
            </div>
            <div class="mx-auto">
               <svg
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                  style="
                  margin:auto
                  background: rgb(255, 255, 255);
                  display: block;
                  shape-rendering: auto;
                  animation-play-state: running;
                  animation-delay: 0s;
                  "
                  width="250px"
                  height="250px"
                  viewBox="0 0 100 100"
                  preserveAspectRatio="xMidYMid"
               >
                  <circle
                  cx="50"
                  cy="50"
                  r="19"
                  stroke-width="5"
                  stroke="#002147"
                  stroke-dasharray="29.845130209103033 29.845130209103033"
                  fill="none"
                  stroke-linecap="round"
                  style="animation-play-state: running; animation-delay: 0s"
                  >
                  <animateTransform
                     attributeName="transform"
                     type="rotate"
                     dur="1s"
                     repeatCount="indefinite"
                     keyTimes="0;1"
                     values="0 50 50;360 50 50"
                     style="animation-play-state: running; animation-delay: 0s"
                  ></animateTransform>
                  </circle>
                  <circle
                  cx="50"
                  cy="50"
                  r="13"
                  stroke-width="5"
                  stroke="#4270a9"
                  stroke-dasharray="20.420352248333657 20.420352248333657"
                  stroke-dashoffset="20.420352248333657"
                  fill="none"
                  stroke-linecap="round"
                  style="animation-play-state: running; animation-delay: 0s"
                  >
                  <animateTransform
                     attributeName="transform"
                     type="rotate"
                     dur="1s"
                     repeatCount="indefinite"
                     keyTimes="0;1"
                     values="0 50 50;-360 50 50"
                     style="animation-play-state: running; animation-delay: 0s"
                  ></animateTransform>
                  </circle>
                  <!-- [ldio] generated by https://loading.io/ -->
               </svg>
            </div>
         </v-card>
   </div>
   <div v-else>
      <v-card flat v-if="photo_galleries.length === 0" height="480" min-height="300">
         <v-container fill-height fluid>
            <v-row align="center" justify="center">
               <div class="text-center">
                  <h1>No Galleries Has Been Added Yet !!</h1>
                  <h2>Add Galleries From The Admin Panel.</h2>
               </div>
            </v-row>
         </v-container>
      </v-card>
      <div v-else>      
         <v-row class="mx-2 py-2">         
            <v-card flat tile class="mx-auto">
               <v-card-title class="text-center text-h3 blue--text text--darken-4">
                  Photo Gallery
               </v-card-title>
            </v-card>
         </v-row>
         <v-row>
            <v-col v-for="(photo_gallery, index) in photo_galleries" :key="index" cols="12" md="6">
               <v-card
                  class="mx-auto"
                  :to="'/single-gallery/' + photo_gallery.id"
               >
                  <v-img
                     :src="'/storage/gallery_cover_photos/' + photo_gallery.gallery_cover_photo"
                     height="400"
                     width="auto"
                  ></v-img>
                  <v-card-title>
                     {{ photo_gallery.gallery_name }}
                  </v-card-title>
                  <v-card-subtitle>
                     Created: {{  moment(photo_gallery.created_at).format('MMMM Do YYYY, h:mm a') }}
                  </v-card-subtitle>
               </v-card>
            </v-col>
         </v-row>
      </div>
   </div> 
</div>
</template>

<script>
import moment from 'moment'
export default {
   data: () => ({
      photo_galleries:[],
      moment: moment,
      loading: true,
      show: false,
   }),
   created() {
      axios
         .get("/api/gallery/name/index")
         .then((res) => {            
            this.photo_galleries = res.data;
            this.loading = false;
         })
         .catch((error) => {
            console.log(error);
            // this.errors = error.response.data.errors
            this.loading = false;
         });
   },
};
</script>

<style>

</style>