<template>
<div class="pt-3">  
   <div v-if="loading">
      <v-card flat class="mt-6">
         <div class="text-center blue--text text--darken-4 font-weight-bold">
               Loading...
         </div>
         <div class="mx-auto">
            <svg
               xmlns="http://www.w3.org/2000/svg"
               xmlns:xlink="http://www.w3.org/1999/xlink"
               style="
               margin:auto
               background: rgb(255, 255, 255);
               display: block;
               shape-rendering: auto;
               animation-play-state: running;
               animation-delay: 0s;
               "
               width="250px"
               height="250px"
               viewBox="0 0 100 100"
               preserveAspectRatio="xMidYMid"
            >
               <circle
               cx="50"
               cy="50"
               r="19"
               stroke-width="5"
               stroke="#002147"
               stroke-dasharray="29.845130209103033 29.845130209103033"
               fill="none"
               stroke-linecap="round"
               style="animation-play-state: running; animation-delay: 0s"
               >
               <animateTransform
                  attributeName="transform"
                  type="rotate"
                  dur="1s"
                  repeatCount="indefinite"
                  keyTimes="0;1"
                  values="0 50 50;360 50 50"
                  style="animation-play-state: running; animation-delay: 0s"
               ></animateTransform>
               </circle>
               <circle
               cx="50"
               cy="50"
               r="13"
               stroke-width="5"
               stroke="#4270a9"
               stroke-dasharray="20.420352248333657 20.420352248333657"
               stroke-dashoffset="20.420352248333657"
               fill="none"
               stroke-linecap="round"
               style="animation-play-state: running; animation-delay: 0s"
               >
               <animateTransform
                  attributeName="transform"
                  type="rotate"
                  dur="1s"
                  repeatCount="indefinite"
                  keyTimes="0;1"
                  values="0 50 50;-360 50 50"
                  style="animation-play-state: running; animation-delay: 0s"
               ></animateTransform>
               </circle>
               <!-- [ldio] generated by https://loading.io/ -->
            </svg>
         </div>
      </v-card>
   </div>
   <div v-else>
      <v-card flat v-if="publications.publications.length === 0" height="480" min-height="300">
         <v-container fill-height fluid>
            <v-row align="center" justify="center">
               <div class="text-center">
                  <h1>No Publications For This Publication Type Has Been Added Yet !!</h1>
                  <h2>Add Publications For This Publication Type From The Admin Panel.</h2>
               </div>
            </v-row>
         </v-container>
      </v-card>
      <v-row v-else class="mx-2 py-4">
         <v-row>
            <v-card flat tile class="mx-auto mb-4">
               <v-card-title class="text-center text-h3 blue--text text--darken-4 text-uppercase">
                  {{ publications.publication_type_name }}
               </v-card-title>
            </v-card>            
         </v-row>
         <v-col cols="12">
            <v-card v-for="(single_publication, index) in publications.publications" :key="index" :href="'/storage/publication_files/' + single_publication.publication_file" rounded="0" class="mb-4">
            <v-alert color="deep-purple accent-3" class="px-0 py-0 mx-0 my-0" rounded="0" text>
               <v-card-title class="py-2 text-h6 font-weight-medium">
                  <v-icon left color="deep-purple accent-3" large>
                  mdi-pdf-box
                  </v-icon>
                  {{ single_publication.publication_name }}
               </v-card-title>
            </v-alert>
            </v-card>
         </v-col>
      </v-row>
   </div> 
</div>
</template>

<script>
import moment from 'moment'
export default {
   data: () => ({
      publications:null,
      moment: moment,
      loading: true,
   }),
   computed: {
      cardBorderColor: function(){
         return {border: '1px solid #4270a9'}
      }
   },
   created() {
      if( this.$store.state.authenticated.publication_tokens.length > 0 ){
         // Find token by publication_type_info_id using looping
         for (var i = 0; i < this.$store.state.authenticated.publication_tokens.length; i++){
            // look for the entry with a matching `code` value
            if (this.$store.state.authenticated.publication_tokens[i].publication_type_info_id == this.$route.params.id){
               axios
                  .post("/api/publication_token/token_exists", this.$store.state.authenticated.publication_tokens[i])
                  .then((res) => {
                     // console.log(res)
                     if (res.data !== 'token_exists'){
                        console.log('Das Boot !!')
                        this.$store.dispatch('authenticated/reset_state')
                        this.$router.push('/publications_auth/' + this.$route.params.id + '?fail=notokenmatch')
                     }                        
                  }).
                  catch((error) => {
                     this.$store.dispatch('authenticated/reset_state')
                     this.$router.push('/publications_auth/' + this.$route.params.id + '?fail=notokenmatch')
                  })
            }
         }
      }
      else{
         this.$router.push('/publications_auth/' + this.$route.params.id + '?fail=notokens')
      }

      axios
         .get("/api/publication_type_info/show_with_publications/" + this.$route.params.id)
         .then((res) => {
            // console.log(res)
            this.publications = res.data;
            this.loading = false;
         })
         .catch((error) => {
            // console.log(error);
            // this.errors = error.response.data.errors
            // this.loading = false;
            this.$router.push({ name: 'ResourceNotFound' })
         });
   },
};
</script>

<style>
</style>