<template>
  <div>    
    <div v-if="loading">
      <v-card flat>
        <div class="text-center blue--text text--darken-4 font-weight-bold pt-10">
              Loading...
        </div>
        <div class="mx-auto">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              style="
              margin:auto
              background: rgb(255, 255, 255);
              display: block;
              shape-rendering: auto;
              animation-play-state: running;
              animation-delay: 0s;
              "
              width="250px"
              height="250px"
              viewBox="0 0 100 100"
              preserveAspectRatio="xMidYMid"
            >
              <circle
              cx="50"
              cy="50"
              r="19"
              stroke-width="5"
              stroke="#002147"
              stroke-dasharray="29.845130209103033 29.845130209103033"
              fill="none"
              stroke-linecap="round"
              style="animation-play-state: running; animation-delay: 0s"
              >
              <animateTransform
                  attributeName="transform"
                  type="rotate"
                  dur="1s"
                  repeatCount="indefinite"
                  keyTimes="0;1"
                  values="0 50 50;360 50 50"
                  style="animation-play-state: running; animation-delay: 0s"
              ></animateTransform>
              </circle>
              <circle
              cx="50"
              cy="50"
              r="13"
              stroke-width="5"
              stroke="#4270a9"
              stroke-dasharray="20.420352248333657 20.420352248333657"
              stroke-dashoffset="20.420352248333657"
              fill="none"
              stroke-linecap="round"
              style="animation-play-state: running; animation-delay: 0s"
              >
              <animateTransform
                  attributeName="transform"
                  type="rotate"
                  dur="1s"
                  repeatCount="indefinite"
                  keyTimes="0;1"
                  values="0 50 50;-360 50 50"
                  style="animation-play-state: running; animation-delay: 0s"
              ></animateTransform>
              </circle>
              <!-- [ldio] generated by https://loading.io/ -->
            </svg>
        </div>
      </v-card>
    </div>
    <div v-else>
      <v-card flat v-if="resources.resources.length === 0" height="480" min-height="300">
        <v-container fill-height fluid>
          <v-row align="center" justify="center">
              <div class="text-center">
                <h1>No Resources Has Been Added Yet !!</h1>
                <h2>Add Resources From The Admin Panel.</h2>
              </div>
          </v-row>
        </v-container>
      </v-card>
      <!-- <v-row v-else class="mx-2 py-4"> -->
      <div v-else class="grey lighten-3 mt-3">
          <v-card flat tile class="mx-auto grey lighten-3">
              <v-card-subtitle class="text-center text-h3 blue--text text--darken-4 lighten-3 text-uppercase">
                {{ resources.resource_type_name }}
              </v-card-subtitle>
          </v-card>        
        
          <v-sheet class="px-2 py-2" color="grey lighten-3" min-height="500">
            
            <v-card v-for="(resource, index) in resources.resources" :key="index" :href="'/storage/resource_files/' + resource.resource_file" rounded="0" class="mb-4">
              <v-alert color="teal accent-4" class="px-0 py-0 mx-0 my-0" rounded="0" text>
                <v-card-title class="py-2 text-h6 font-weight-medium">
                  <v-icon left color="teal accent-4" large>
                    mdi-pdf-box
                  </v-icon>
                    {{ resource.resource_name }}
                </v-card-title>
              </v-alert>
            </v-card>

            <v-card v-for="(resource, index) in resources.resources" :key="index" :href="'/storage/resource_files/' + resource.resource_file" rounded="0" class="mb-4">
              <v-alert color="teal accent-4" class="px-0 py-0 mx-0 my-0" rounded="0" text>
                <v-card-title class="py-2 text-h6 font-weight-medium">
                  <v-icon left color="teal accent-4" large>
                    mdi-file-pdf-box
                  </v-icon>
                    {{ resource.resource_name }}
                </v-card-title>
              </v-alert>
            </v-card>
          </v-sheet>

      </div>
    </div>
  </div>
</template>

<script>
import moment from 'moment'
export default {
  data: () => ({
      resources:[],
      moment: moment,
      loading: true,
  }),
  computed: {
    
  },
  created() {
    axios.get("/api/resource_type/show/" + this.$route.params.id)
      .then((res) => {        
        this.resources = res.data;
        this.loading = false;
      })
      .catch((error) => {
        console.log(error);
        // this.errors = error.response.data.errors
        this.loading = false;
      });
  },
}
</script>

<style>

</style>