<template>
  <div class="pt-3">     
      <div v-if="loading">
          <v-card flat class="mt-6">
              <div class="text-center blue--text text--darken-4 font-weight-bold">
                    Loading...         
              </div>
              <div class="mx-auto">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    style="
                    margin:auto
                    background: rgb(255, 255, 255);
                    display: block;
                    shape-rendering: auto;
                    animation-play-state: running;
                    animation-delay: 0s;
                    "
                    width="250px"
                    height="250px"
                    viewBox="0 0 100 100"
                    preserveAspectRatio="xMidYMid"
                >
                    <circle
                    cx="50"
                    cy="50"
                    r="19"
                    stroke-width="5"
                    stroke="#002147"
                    stroke-dasharray="29.845130209103033 29.845130209103033"
                    fill="none"
                    stroke-linecap="round"
                    style="animation-play-state: running; animation-delay: 0s"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;360 50 50"
                        style="animation-play-state: running; animation-delay: 0s"
                    ></animateTransform>
                    </circle>
                    <circle
                    cx="50"
                    cy="50"
                    r="13"
                    stroke-width="5"
                    stroke="#4270a9"
                    stroke-dasharray="20.420352248333657 20.420352248333657"
                    stroke-dashoffset="20.420352248333657"
                    fill="none"
                    stroke-linecap="round"
                    style="animation-play-state: running; animation-delay: 0s"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;-360 50 50"
                        style="animation-play-state: running; animation-delay: 0s"
                    ></animateTransform>
                    </circle>
                    <!-- [ldio] generated by https://loading.io/ -->
                </svg>
              </div>
          </v-card>
      </div>
      <div v-else>
         <v-row>
            <v-card flat tile class="mx-auto mt-2">
               <v-card-title class="text-center text-h3 blue--text text--darken-4">
                  NEWS
               </v-card-title>
            </v-card>
         </v-row>
         <v-row class="mx-1 py-2 mt-n3">
            <v-col cols="12">
               <v-card min-height="450" class="mx-4 pb-4" elevation="10">
                  <v-card-text class="text-subtitle-1 mt-1 pb-0 orange--text text--darken-3"> HEADLINE: </v-card-text>
                  <v-card-title class="text-h6 mb-1 pt-0">
                     {{ single_news.news_title }}
                  </v-card-title>

                  <v-img                     
                     width="auto"
                     max-height="700"
                     :src="'/storage/news_images/' + single_news.news_image"
                     alt=""
                     position="center center"
                     aspect-ratio="2"
                  ></v-img>

                  <v-card-subtitle class="text-subtitle-1 orange--text text--darken-3">
                     Date Published: {{ moment(single_news.created_at).format('MMMM Do YYYY, h:mm a') }}
                  </v-card-subtitle>

                  <v-card-text class="text-subtitle-1 font-weight-medium black--text">
                     <div class="text-subtitle-1 orange--text text--darken-3"> DETAILS: </div>
                     {{ single_news.news_text }}
                  </v-card-text>
                  
               </v-card>
            </v-col>
         </v-row>
      </div>
   </div>
</template>

<script>
import moment from 'moment'
export default {
   data: () => ({
      single_news: null,
      moment: moment,
      loading: true,
   }),
   created() {
      axios
         .get("/api/news/show/" + this.$route.params.id)
         .then((res) => {
            this.single_news = res.data;
            this.loading = false;
         })
         .catch((error) => {
            // console.log(error);
            // this.errors = error.response.data.errors
            this.$router.push({ name: 'ResourceNotFound' })            
         });
   },
};
</script>

<style>

</style>