<template>
   <div class="pt-3">      
      <div v-if="loading">
         <v-card flat class="mt-6">
            <div class="text-center blue--text text--darken-4 font-weight-bold">
               Loading...
            </div>
            <div class="mx-auto">
               <svg
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                  style="
                    margin:auto
                    background: rgb(255, 255, 255);
                    display: block;
                    shape-rendering: auto;
                    animation-play-state: running;
                    animation-delay: 0s;
                    "
                  width="250px"
                  height="250px"
                  viewBox="0 0 100 100"
                  preserveAspectRatio="xMidYMid"
               >
                  <circle
                     cx="50"
                     cy="50"
                     r="19"
                     stroke-width="5"
                     stroke="#002147"
                     stroke-dasharray="29.845130209103033 29.845130209103033"
                     fill="none"
                     stroke-linecap="round"
                     style="animation-play-state: running; animation-delay: 0s"
                  >
                     <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;360 50 50"
                        style="
                           animation-play-state: running;
                           animation-delay: 0s;
                        "
                     ></animateTransform>
                  </circle>
                  <circle
                     cx="50"
                     cy="50"
                     r="13"
                     stroke-width="5"
                     stroke="#4270a9"
                     stroke-dasharray="20.420352248333657 20.420352248333657"
                     stroke-dashoffset="20.420352248333657"
                     fill="none"
                     stroke-linecap="round"
                     style="animation-play-state: running; animation-delay: 0s"
                  >
                     <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;-360 50 50"
                        style="
                           animation-play-state: running;
                           animation-delay: 0s;
                        "
                     ></animateTransform>
                  </circle>
                  <!-- [ldio] generated by https://loading1.io/ -->
               </svg>
            </div>
         </v-card>
      </div>
      <div v-else>
         <v-card flat v-if="photos.gallery_photos.length === 0" height="480" min-height="300">
            <v-container fill-height fluid>
               <v-row align="center" justify="center">
                  <div class="text-center">
                     <h1>No Photos Have Been Added To The Gallery Yet !!</h1>
                     <h2>Add Photos To This Gallery From The Admin Panel.</h2>
                  </div>
               </v-row>
            </v-container>
         </v-card>
         <div v-else>
            <v-card flat tile class="mx-auto">
               <v-card-subtitle class="text-center text-h3 blue--text text--darken-4 lighten-3 text-uppercase">
                  {{ photos.gallery_name }}
               </v-card-subtitle>
            </v-card>
            <v-row class="mx-1 py-2 mt-n3">
               <v-col
                  v-for="(photo, index) in photos.gallery_photos"
                  :key="index"
                  cols="12"
                  sm="6"
                  md="4"
               >               
                  <v-card flat>
                     <v-img
                        :src="photo.src"
                        @click="showSingle(photo.src, photo.title, index)"
                        aspect-ratio="1"
                     >
                     </v-img>
                     <v-card-text class="font-weight-medium text-subtitle-2 pt-1">
                        {{ photo.title }}
                     </v-card-text>
                  </v-card>
               </v-col>
            </v-row>

            <!-- all props & events -->
            <vue-easy-lightbox
               escDisabled
               moveDisabled
               :visible="visible"
               :imgs="photos.gallery_photos"
               :index="index"
               @hide="handleHide"
            >
            </vue-easy-lightbox>
         </div>
      </div>
   </div>
</template>

<script>
// Import Vue Easy Lightbox Component
import VueEasyLightbox from "vue-easy-lightbox";
export default {
   components: {
      VueEasyLightbox,
   },
   data() {
      return {
         photos: "", // Img Url , string or Array of string
         single_photo: "",
         title: "",
         visible: false,
         index: 0, // default: 0         
         loading: true,         
      };
   },
   methods: {
      showSingle(photo, title, index) {
         this.single_photo = photo;
         this.title = title;
         this.index = index;
         this.show();
      },

      show() {
         this.visible = true;
      },
      handleHide() {
         this.visible = false;
      },
   },
   created() {

      axios
         .get("/api/gallery/name/show/" + this.$route.params.id)
         .then((res) => {
            // console.log(res)
            this.photos = res.data;
            this.loading = false;
         })
         .catch((error) => {
            // console.log(error);
            // this.errors = error.response.data.errors
            // this.loading2 = false;
            this.$router.push({ name: 'ResourceNotFound' })
         });
   },
};
</script>