<template>
   <div>
      <!-- {{carousel_content}} -->
      <div v-if="loading_content">
         <div class="text-h6 text-center blue--text text--darken-4 font-weight-bold pt-10">
               Loading...
         </div>
         <div>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%; display: block; shape-rendering: auto;" width="291px" height="291px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
               <g transform="rotate(0 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.9090909090909091s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(32.72727272727273 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.8181818181818182s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(65.45454545454545 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.7272727272727273s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(98.18181818181819 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.6363636363636364s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(130.9090909090909 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5454545454545454s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(163.63636363636363 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.45454545454545453s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(196.36363636363637 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.36363636363636365s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(229.0909090909091 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.2727272727272727s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(261.8181818181818 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.18181818181818182s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(294.54545454545456 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.09090909090909091s" repeatCount="indefinite"></animate>
               </rect>
               </g><g transform="rotate(327.27272727272725 50 50)">
               <rect x="47.5" y="28.5" rx="2.5" ry="4.5" width="5" height="9" fill="#85a2b6">
                  <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="0s" repeatCount="indefinite"></animate>
               </rect>
               </g>
               <!-- [ldio] generated by https://loading.io/ -->
            </svg>
         </div>
      </div>

      <v-card v-else>
         <v-card flat tile outlined width="100%">
            <v-card-title> Carousel Content </v-card-title>
         </v-card>

         <div v-for="(carousel_content, index) in carousel_content" :key="index">
            <v-card tile outlined class="mx-auto px-1 py-1">
               <v-card-title class="py-1">
                  <span class="text-h6 font-weight-medium"> {{ carousel_content.carousel_title }} Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid placeat sed labore aliquam ut corrupti reprehenderit facilis esse eius quidem. </span>
               </v-card-title>

               <v-card-text class="text-body-1 font-weight-medium py-0">
                  {{ carousel_content.carousel_title }} Lorem ipsum dolor sit amet consectetur adipisicing elit. A totam optio vel eaque nulla omnis, placeat eveniet. Odio, delectus totam.
               </v-card-text>

               <v-card-actions class="py-0">
                  <v-list-item class="grow">

                     <v-list-item-avatar color="grey darken-3" tile width="150" height="100">
                        <v-img
                           class="elevation-6"
                           :src="'/storage/carousel_images/' + carousel_content.carousel_image"
                           alt=""
                           position="center center"
                           aspect-ratio="2"
                        ></v-img>
                     </v-list-item-avatar>

                     <v-row
                        align="center"
                        justify="end"
                     >
                        <v-btn elevation="2" fab rounded class="ma-1 indigo darken-3 rounded-1">
                           <v-icon color="white">
                              mdi-clipboard-edit
                           </v-icon>
                        </v-btn>
                        <v-btn elevation="2" fab rounded class="ma-1 red darken-4 rounded-1">
                           <v-icon color="white">
                              mdi-trash-can
                           </v-icon>
                        </v-btn>
                     </v-row>

                  </v-list-item>
               </v-card-actions>
            </v-card>
         </div>
      </v-card>
   </div>
</template>

<script>
export default {
   data: () => ({
      cards: ["Today", "Yesterday"],
      carousel_content: [],
      loading_content: false,
   }),
   methods: {
      // logout() {
      //    axios.post("/api/carouselcontent/index")
      //    .then((response) => {
      //       this.carousel_content = response.data
      //    });
      // },
   },
   created() {
      this.loading_content = true,
      axios.get("/api/carouselcontent/index")
         .then((response) => {
            console.log("response");
            this.carousel_content = response.data
            this.loading_content = false
         });
   },
};
</script>

<style>
</style>