<template>
  <div class="pt-3">
     {{ photos }}
     {{ gallery_title }}
      <div v-if="loading1 && loading2">
          <v-card flat class="mt-6">
              <div class="text-center blue--text text--darken-4 font-weight-bold">
                    Loading...         
              </div>
              <div class="mx-auto">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    style="
                    margin:auto
                    background: rgb(255, 255, 255);
                    display: block;
                    shape-rendering: auto;
                    animation-play-state: running;
                    animation-delay: 0s;
                    "
                    width="250px"
                    height="250px"
                    viewBox="0 0 100 100"
                    preserveAspectRatio="xMidYMid"
                >
                    <circle
                    cx="50"
                    cy="50"
                    r="19"
                    stroke-width="5"
                    stroke="#002147"
                    stroke-dasharray="29.845130209103033 29.845130209103033"
                    fill="none"
                    stroke-linecap="round"
                    style="animation-play-state: running; animation-delay: 0s"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;360 50 50"
                        style="animation-play-state: running; animation-delay: 0s"
                    ></animateTransform>
                    </circle>
                    <circle
                    cx="50"
                    cy="50"
                    r="13"
                    stroke-width="5"
                    stroke="#4270a9"
                    stroke-dasharray="20.420352248333657 20.420352248333657"
                    stroke-dashoffset="20.420352248333657"
                    fill="none"
                    stroke-linecap="round"
                    style="animation-play-state: running; animation-delay: 0s"
                    >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;-360 50 50"
                        style="animation-play-state: running; animation-delay: 0s"
                    ></animateTransform>
                    </circle>
                    <!-- [ldio] generated by https://loading1.io/ -->
                </svg>
              </div>
          </v-card>
      </div>
      <div v-else>
         <div class="text-center">
            <v-overlay :value="toggle_overlay">
               <!-- Working Image with Overlay with Disable on Click. -->
               <!-- <div>
                  <v-img
                     contain
                     v-click-outside="disableOverlay"
                     :src="'/storage/photo_gallery_images/' + overlay_image"
                     max-width="1000"
                     max-height="600"
                  >
                  </v-img>
                  <div> Click Outside to Exit </div>
               </div> -->

               <!-- Carousel Component Working but image ratios are off. Kept as reference. -->
               <v-carousel v-model="image_index" v-click-outside="disableOverlay">
                  <v-carousel-item
                     v-for="(photo, index) in photos"
                     :key="index"                     
                     :src="'/storage/photo_gallery_images/' + photo.photo_image"
                     @click="show_image(photo.photo_image)"                     
                  >
                  </v-carousel-item>
               </v-carousel>
            </v-overlay>
         </div>
         <v-row>
            <v-card flat tile class="mx-auto mt-2">
               <v-card-title class="text-center text-h3 blue--text text--darken-4">
                  {{ gallery_title.gallery_name }}
               </v-card-title>
            </v-card>
         </v-row>
         <v-row class="mx-1 py-2 mt-n3">
            <v-col v-for="(photo, index) in photos" :key="index" cols="12" sm="6" md="4">               
               <v-img
               :src="'/storage/photo_gallery_images/' + photo.photo_image"
               :alt="'Image - ' + photo.photo_image"
               @click="show_image(photo.photo_image, index)"
               height="400"
               width="auto"
               >
               </v-img>
            </v-col>
         </v-row>
      </div>
   </div>
</template>

<script>
import moment from 'moment'
export default {
   data: () => ({
      photos: [],
      gallery_title: null,
      moment: moment,
      loading1: true,
      loading2: true,
      toggle_overlay: false,
      overlay_image: null,
      image_index: 0,
   }),
   methods: {
      show_image(image, index){
         this.overlay_image = image
         this.image_index = index
         this.toggle_overlay = true
      },
      disableOverlay(){
         this.toggle_overlay = false
      }
   },
   created() {
      axios
         .get("/api/gallery/photos/photosbygalleryid/" + this.$route.params.id)
         .then((res) => {
            this.photos = res.data;
            this.loading1 = false;
         })
         .catch((error) => {
            console.log(error);
            // this.errors = error.response.data.errors
            this.loading1 = false;
         });

      axios
         .get("/api/gallery/name/show/" + this.$route.params.id)
         .then((res) => {            
            this.gallery_title = res.data;
            this.loading2 = false;
         })
         .catch((error) => {
            console.log(error);
            // this.errors = error.response.data.errors
            this.loading2 = false;
         });
   },
};
</script>

<style>

</style>